/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as DeliveryIndexRouteImport } from './routes/delivery/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserOrdersRouteImport } from './routes/user/orders'
import { Route as UserMenuRouteImport } from './routes/user/menu'
import { Route as UserLoginRouteImport } from './routes/user/login'
import { Route as UserLoadingRouteImport } from './routes/user/loading'
import { Route as UserCheckoutRouteImport } from './routes/user/checkout'
import { Route as UserCartRouteImport } from './routes/user/cart'
import { Route as DeliveryProfileRouteImport } from './routes/delivery/profile'
import { Route as DeliveryLoginRouteImport } from './routes/delivery/login'
import { Route as DeliveryHistoryRouteImport } from './routes/delivery/history'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardMenuRouteImport } from './routes/dashboard/menu'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardDeliveryRouteImport } from './routes/dashboard/delivery'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard/categories'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeliveryRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserOrdersRoute = UserOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => UserRoute,
} as any)
const UserMenuRoute = UserMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => UserRoute,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UserRoute,
} as any)
const UserLoadingRoute = UserLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => UserRoute,
} as any)
const UserCheckoutRoute = UserCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => UserRoute,
} as any)
const UserCartRoute = UserCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => UserRoute,
} as any)
const DeliveryProfileRoute = DeliveryProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryLoginRoute = DeliveryLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryHistoryRoute = DeliveryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DeliveryRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliveryRoute = DashboardDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/delivery': typeof DeliveryRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/user/cart': typeof UserCartRoute
  '/user/checkout': typeof UserCheckoutRoute
  '/user/loading': typeof UserLoadingRoute
  '/user/login': typeof UserLoginRoute
  '/user/menu': typeof UserMenuRoute
  '/user/orders': typeof UserOrdersRoute
  '/user/profile': typeof UserProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/user/cart': typeof UserCartRoute
  '/user/checkout': typeof UserCheckoutRoute
  '/user/loading': typeof UserLoadingRoute
  '/user/login': typeof UserLoginRoute
  '/user/menu': typeof UserMenuRoute
  '/user/orders': typeof UserOrdersRoute
  '/user/profile': typeof UserProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/delivery': typeof DeliveryIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/delivery': typeof DeliveryRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/user/cart': typeof UserCartRoute
  '/user/checkout': typeof UserCheckoutRoute
  '/user/loading': typeof UserLoadingRoute
  '/user/login': typeof UserLoginRoute
  '/user/menu': typeof UserMenuRoute
  '/user/orders': typeof UserOrdersRoute
  '/user/profile': typeof UserProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/delivery'
    | '/user'
    | '/dashboard/analytics'
    | '/dashboard/categories'
    | '/dashboard/customers'
    | '/dashboard/delivery'
    | '/dashboard/inventory'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/delivery/history'
    | '/delivery/login'
    | '/delivery/profile'
    | '/user/cart'
    | '/user/checkout'
    | '/user/loading'
    | '/user/login'
    | '/user/menu'
    | '/user/orders'
    | '/user/profile'
    | '/dashboard/'
    | '/delivery/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/analytics'
    | '/dashboard/categories'
    | '/dashboard/customers'
    | '/dashboard/delivery'
    | '/dashboard/inventory'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/delivery/history'
    | '/delivery/login'
    | '/delivery/profile'
    | '/user/cart'
    | '/user/checkout'
    | '/user/loading'
    | '/user/login'
    | '/user/menu'
    | '/user/orders'
    | '/user/profile'
    | '/dashboard'
    | '/delivery'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/delivery'
    | '/user'
    | '/dashboard/analytics'
    | '/dashboard/categories'
    | '/dashboard/customers'
    | '/dashboard/delivery'
    | '/dashboard/inventory'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/delivery/history'
    | '/delivery/login'
    | '/delivery/profile'
    | '/user/cart'
    | '/user/checkout'
    | '/user/loading'
    | '/user/login'
    | '/user/menu'
    | '/user/orders'
    | '/user/profile'
    | '/dashboard/'
    | '/delivery/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeliveryRoute: typeof DeliveryRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/'
      fullPath: '/delivery/'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/orders': {
      id: '/user/orders'
      path: '/orders'
      fullPath: '/user/orders'
      preLoaderRoute: typeof UserOrdersRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/menu': {
      id: '/user/menu'
      path: '/menu'
      fullPath: '/user/menu'
      preLoaderRoute: typeof UserMenuRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/login': {
      id: '/user/login'
      path: '/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/loading': {
      id: '/user/loading'
      path: '/loading'
      fullPath: '/user/loading'
      preLoaderRoute: typeof UserLoadingRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/checkout': {
      id: '/user/checkout'
      path: '/checkout'
      fullPath: '/user/checkout'
      preLoaderRoute: typeof UserCheckoutRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/cart': {
      id: '/user/cart'
      path: '/cart'
      fullPath: '/user/cart'
      preLoaderRoute: typeof UserCartRouteImport
      parentRoute: typeof UserRoute
    }
    '/delivery/profile': {
      id: '/delivery/profile'
      path: '/profile'
      fullPath: '/delivery/profile'
      preLoaderRoute: typeof DeliveryProfileRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/login': {
      id: '/delivery/login'
      path: '/login'
      fullPath: '/delivery/login'
      preLoaderRoute: typeof DeliveryLoginRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/history': {
      id: '/delivery/history'
      path: '/history'
      fullPath: '/delivery/history'
      preLoaderRoute: typeof DeliveryHistoryRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/delivery': {
      id: '/dashboard/delivery'
      path: '/delivery'
      fullPath: '/dashboard/delivery'
      preLoaderRoute: typeof DashboardDeliveryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDeliveryRoute: typeof DashboardDeliveryRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDeliveryRoute: DashboardDeliveryRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DeliveryRouteChildren {
  DeliveryHistoryRoute: typeof DeliveryHistoryRoute
  DeliveryLoginRoute: typeof DeliveryLoginRoute
  DeliveryProfileRoute: typeof DeliveryProfileRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryHistoryRoute: DeliveryHistoryRoute,
  DeliveryLoginRoute: DeliveryLoginRoute,
  DeliveryProfileRoute: DeliveryProfileRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface UserRouteChildren {
  UserCartRoute: typeof UserCartRoute
  UserCheckoutRoute: typeof UserCheckoutRoute
  UserLoadingRoute: typeof UserLoadingRoute
  UserLoginRoute: typeof UserLoginRoute
  UserMenuRoute: typeof UserMenuRoute
  UserOrdersRoute: typeof UserOrdersRoute
  UserProfileRoute: typeof UserProfileRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserCartRoute: UserCartRoute,
  UserCheckoutRoute: UserCheckoutRoute,
  UserLoadingRoute: UserLoadingRoute,
  UserLoginRoute: UserLoginRoute,
  UserMenuRoute: UserMenuRoute,
  UserOrdersRoute: UserOrdersRoute,
  UserProfileRoute: UserProfileRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeliveryRoute: DeliveryRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
